name: mappable_maps_navikit
description: Mappable MapKit SDK for Flutter. This allow you to use the capabilities
  of Mappable.Maps in your Flutter applications for iOS and Android
version: 4.8.1-beta
repository: https://github.com/mappable-world/mappable_maps_navikit
environment:
  sdk: ^3.1.0
  flutter: '>=3.13.1'
dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  uuid: ^4.2.2
  flutter_plugin_android_lifecycle: ^2.0.16
  meta: ^1.9.1
dev_dependencies:
  build_runner: null
  source_gen: null
  init:
    path: codegen/init
flutter:
  plugin:
    platforms:
      android:
        package: world.mappable.maps.flutter
        pluginClass: MappableMapsPlugin
      ios:
        pluginClass: MappableMapsPlugin
